name: "Deploy docs"

on: 
  workflow_dispatch
    inputs:
      type:
        description: "the release type"
        required: true
      repo:
        description: "the target repo for the docs"
        required: true
      base:
        description: "the base dir for the docs of the repo"
        required: true

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish
        id: projects
        uses: ./.github/actions/publish
        with:
          type: ${{github.event.inputs.type}}
          repo: ${{github.event.inputs.repo}}
          base: ${{github.event.inputs.base}}
