name: "Deploy docs"

on: push
# on:
#   workflow_dispatch:
#     inputs:
#       type:
#         description: "the release type"
#         required: true
#       repo:
#         description: "the target repo for the docs"
#         required: true
#       branch:
#         description: "the branch for the docs we want to publish"
#         required: true

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - run: whereis google-chrome
      # - uses: actions/checkout@v2
      # - name: publish
      #   id: projects
      #   uses: ./.github/actions/publish
      #   with:
      #     type: ${{github.event.inputs.type}}
      #     repo: ${{github.event.inputs.repo}}
      #     branch: ${{github.event.inputs.branch}}
      #     token: ${{ secrets.WORKFLOW_TOKEN }}
